#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd bash &&
cat bashrc_default > bashrc &&
echo -e "\n" >> bashrc &&
cat bashrc_custom >> bashrc &&
mv bashrc ~/.bashrc &&
cp bash_profile ~/.bash_profile &&
echo -e "${green}Installed bash config!${default}" ||
echo -e "${red}Failed to install bash config!${default}"
