#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd atom &&
rm -f ~/.atom/config.cson &&
mkdir -p ~/.atom &&
cp config.cson ~/.atom/ &&
# rm ~/.atom/keymap.cson &&
# cp keymap.cson ~/.atom &&
echo -e "${green}Installed atom config!${default}" ||
echo -e "${red}Failed to install atom config!${default}"
