#!/bin/bash

default="\e[0m"
green="\e[32m"
red="\e[31m"

cd tmux &&
cp tmux.conf ~/.tmux.conf &&
echo -e "${green}Installed tmux config!${default}" ||
echo -e "${red}Failed to install tmux config!${default}"
