#!/bin/bash

cd bash &&
cat bashrc_default > bashrc &&
echo -e "\n" >> bashrc &&
cat bashrc_custom >> bashrc &&
mv bashrc ~/.bashrc &&
cp bash_profile ~/.bash_profile &&
echo "Installed bash config!" ||
echo "Failed to install bash config!"
