#!/bin/bash

default="\e[0m"
green="\e[32m"
red="\e[31m"

rm -rf ~/.config/base16-shell &&
mkdir -p ~/.config &&
rm -rf bash16-shell &&
git clone git@github.com:chriskempson/base16-shell.git &&
mv base16-shell ~/.config/base16-shell &&

cat << 'EOF' >> ~/.bashrc &&

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"
EOF

bash -i -c base16_tomorrow-night &&

echo -e "${green}Installed base16-shell config!${default}" ||
echo -e "${red}Failed to install base16-shell config!${default}"

mkdir -p ~/.vim/colors &&
rm -rf base16-vim &&
git clone git@github.com:chriskempson/base16-vim.git &&
cp -r base16-vim/colors ~/.vim &&
rm -rf base16-vim &&

cat  << 'EOF' >> ~/.vimrc &&

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
EOF

echo -e "${green}Installed base16-vim config!${default}" ||
echo -e "${red}Failed to install base16-vim config!${default}"
