#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd vim &&
rm -f ~/.vimrc &&
cp vimrc ~/.vimrc &&
echo -e "${green}Installed vim config!${default}" ||
echo -e "${red}Failed to installed vim config!${default}"
