#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd tmux &&
cp tmux.conf ~/.tmux.conf &&
echo -e "${green}Installed tmux config!${default}" ||
echo -e "${red}Failed to install tmux config!${default}"
