#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd atom &&
cp config.cson ~/.atom &&
# cp keymap.cson ~/.atom &&
echo -e "${green}Installed atom config!${default}" ||
echo -e "${red}Failed to install atom config!${default}"
