#!/bin/bash

default="\e[0m"
green="\e[32m"
red="\e[31m"

cd vim &&
cp vimrc ~/.vimrc &&
echo -e "${green}Installed vim config!${default}" ||
echo -e "${red}Failed to installed vim config!${default}"
