#!/bin/bash

default=$(tput sgr 0)
green=$(tput setaf 2)
red=$(tput setaf 1)

cd git &&
rm -f ~/.gitconfig &&
cp gitconfig ~/.gitconfig &&
echo -e "${green}Installed git config!${default}" ||
echo -e "${red}Failed to install git config!${default}"
