if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

colorscheme base16-tomorrow-night

syntax on

set smartindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set nu

set cursorline
set colorcolumn=81
